log_level: info

rabbitmq:
  uri: "amqp://guest:guest@localhost:5672/"
  queue: "aml.screening.ogs"
  exchange: "aml.screening.ogs"
  routing_key: "event.#"
  prefetch_count: 10

mongodb:
  uri: "mongodb://localhost:27017"
  database: "cdaq"
  collection: "events"
  job_collection: "jobs"
  child_job_collection: "child_jobs"
